Target guided ordinal encoding

In [1]:
import pandas as pd
df=pd.DataFrame({
    'city':['newyork','london','paris','tokyo','newyork','paris'],
    'price':[200,150,300,250,180,320]
})

In [2]:
df

      city  price
0  newyork    200
1   london    150
2    paris    300
3    tokyo    250
4  newyork    180
5    paris    320

In [4]:
mean_price=df.groupby('city')['price'].mean().to_dict()
mean_price

{'london': 150.0, 'newyork': 190.0, 'paris': 310.0, 'tokyo': 250.0}

In [5]:
df['city_encoded']=df['city'].map(mean_price)

In [9]:
df[['price','city_encoded']]

   price  city_encoded
0    200         190.0
1    150         150.0
2    300         310.0
3    250         250.0
4    180         190.0
5    320         310.0